//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// waifu2xnvgui.Japanese.rc で使用
//
#define IDS_ERROR_TITLE                 105
#define IDS_ERROR_INSTANCE              106
#define IDS_ERROR_EXCEPTION             107
#define IDS_ERROR_SERVER                108
#define IDS_ERROR_DOWNLOAD              109
#define IDS_ERROR_FFMPEG                110
#define IDS_ERROR_WAIFU2X               111
#define IDS_ERROR_IMAGE2PNG             112
#define IDS_ERROR_ABORT                 113
#define IDS_ERROR_APPNOTFOUND           114
#define IDS_ERROR_NOTSELECTED           115
#define IDS_ERROR_SETTINGS              116
#define IDS_ERROR_UPSCALE               117
#define IDS_ERROR_REUPSCALE             118
#define IDS_ERROR_FAILED                119
#define IDS_ERROR_FOLDER                120
#define IDS_ERROR_RESIZE                121
#define IDS_ERROR_SOUND                 122
#define IDS_ERROR_UPDATE                123
#define IDS_ERROR_UPDATE_ELSE           124
#define IDS_ERROR_BLOCKSIZE_LARGE       125
#define IDS_ERROR_BLOCKSIZE_SHORT       126
#define IDS_UPDATE_LATEST               127
#define IDS_UPDATE_CURRENT              128
#define IDS_UPDATE_FFMPEG               129
#define IDS_UPDATE_FFMPEG_TITLE         130
#define IDS_INFO_TITLE                  131
#define IDS_INFO_DOWNLOAD               132
#define IDS_INFO_UPSCALE                133
#define IDS_INFO_UPSCALE_TITLE          134
#define IDS_ERROR_UPSCALE_TITLE         135
#define IDS_INFO_REUPSCALE              136
#define IDS_INFO_REUPSCALE_TITLE        137
#define IDS_ERROR_REUPSCALE_TITLE       138
#define IDS_WARN_ABORT                  139
#define IDS_INFO_SUCCESS                140
#define IDS_WARN_CANCEL                 141
#define IDS_WARN_SAVECANCEL             142
#define IDS_WARN_CONFIRM                143
#define IDS_WARN_EXIST                  144
#define IDS_WARN_ABORT2                 145
#define IDS_INFO_RESIZE                 146
#define IDS_INFO_SOUND                  147
#define IDS_UPDATE_APP_LATEST           148
#define IDS_UPDATE_APP_CONFIRM          149
#define IDS_UPDATE_APP_TITLE            150
#define IDS_WARN_ADVANCED               151
#define IDS_WARN_CAUTION_TITLE          152
#define IDS_TEXT_UNKNOWN                153
#define IDS_WARN_CANCEL_TITLE           154
#define IDS_TEXT_SELFOLDER              155
#define IDS_TEXT_DIRECTORYS             156
#define IDS_TEXT_BYTES                  157
#define IDS_TEXT_SELOUTPUTFOLDER        158
#define IDS_ERROR_IMAGENOT              159
#define IDS_ERROR_IMAGENOT2             160
#define IDS_FILTER_MOVIE                161
#define IDS_FILTER_IMAGE                162
#define IDS_FILTER_JPEG                 163
#define IDS_FILTER_PNG                  164
#define IDS_FILTER_WEBP                 165
#define IDS_FILTER_SOUND                166
#define IDS_MENU_FILE                   167
#define IDS_MENU_CONFIG                 168
#define IDS_MENU_TOOL                   169
#define IDS_MENULIST_READFILE           170
#define IDS_MENULIST_IMG                171
#define IDS_MENULIST_IMGM               172
#define IDS_MENULIST_MOV                173
#define IDS_MENULIST_TEMPFILE           174
#define IDS_MENULIST_ENDAPP             175
#define IDS_MENULIST_WAIFU2X            176
#define IDS_MENULIST_FFMPEG             177
#define IDS_MENULIST_FF_OUT             178
#define IDS_MENULIST_FF_VID             179
#define IDS_MENULIST_FF_AUD             180
#define IDS_MENULIST_RESIZE             181
#define IDS_MENULIST_SOUND              182
#define IDS_MENULIST_UPDATE             183
#define IDS_STATIC_HEADER               184
#define IDS_STATIC_GRP_FILE             185
#define IDS_STATIC_FILEREAD             186
#define IDS_STATIC_FILENAME             187
#define IDS_STATIC_FILEPATH             188
#define IDS_STATIC_NOTREAD              189
#define IDS_STATIC_READED               190
#define IDS_STATIC_GRP_IMG              191
#define IDS_STATIC_GRP_IMGM             192
#define IDS_STATIC_GRP_VID              193
#define IDS_STATIC_GRP_INFO             194
#define IDS_STATIC_CPU                  195
#define IDS_STATIC_GPU                  196
#define IDS_BTN_UPSCALE                 197
#define IDS_BTN_REUPSCALE               198
#define IDS_BTN_MULTIUPSCALE            199
#define IDS_BTN_FINALENC                200
#define IDS_2X_TITLE                    201
#define IDS_GRP_GENERAL                 202
#define IDS_GRP_ADVANCED                203
#define IDS_STATIC_DENOISE              204
#define IDS_STATIC_UPSCALELV            205
#define IDS_STATIC_USEGPU               206
#define IDS_STATIC_BLOCKSIZE            207
#define IDS_STATIC_BLOCK                208
#define IDS_CHECK_ADVANCED              209
#define IDS_STATIC_THREAD               210
#define IDS_STATIC_FORMAT               211
#define IDS_STATIC_MODEL                212
#define IDS_CHECK_VERBOSE               213
#define IDS_CHECK_TTA                   214
#define IDS_STATIC_PARAM                215
#define IDS_FF_SETTING_TITLE            216
#define IDS_FF_VIDDLG_TITLE             217
#define IDS_FF_SNDDLG_TITLE             218
#define IDS_STATIC_PRESET               219
#define IDS_STATIC_VIDFPS               220
#define IDS_STATIC_VIDFPS2              221
#define IDS_STATIC_VIDCODEC             222
#define IDS_STATIC_SNDCODEC             223
#define IDS_STATIC_SNDBIT               224
#define IDS_BTN_FINDCODEC               225
#define IDS_CHECK_HIDEBANNER            226
#define IDS_CHECK_OVERWRITE             227
#define IDS_CHECK_ENABLEAAC             228
#define IDS_CHECK_NVENC_CRF             229
#define IDS_STATIC_CRFLEVEL             230
#define IDS_STATIC_CRFLEVEL2            231
#define IDS_STATIC_FFPATH               232
#define IDS_FF_CODEC_TITLE              233
#define IDS_STATIC_SNDFMT               234
#define IDS_CHECK_SNDONLY               235
#define IDS_CHECK_DSTREAM               236
#define IDS_CHECK_DSTREAM2              237
#define IDS_CHECK_CHAPTERCPY            238
#define IDS_CHECK_MTDATA                239
#define IDS_STATIC_FILENAMENOEXT        240
#define IDS_STATIC_OUTDIRECTRY          241
#define IDS_BTN_CHK                     242
#define IDS_CHK_VIDMULTI                243
#define IDS_RESIZE_TITLE                244
#define IDS_GRP_ASPCT                   245
#define IDS_GRP_SIZE                    246
#define IDS_STATIC_WAITDLG              247
#define IDS_STATIC_THREADDLG            248
#define IDS_BTN_ABORT                   249
#define IDS_STATIC_POPUPDLG             250
#define IDS_STATIC_DLDLG                251
#define IDS_STATIC_DELETEDLG            252
#define IDS_STATIC_ABT_HEADER           253
#define IDS_STATIC_ABT_VER1             254
#define IDS_STATIC_ABT_VER2             255
#define IDS_STATIC_ABT_VER3             256
#define IDS_STATIC_ABT_HYPER1           257
#define IDS_STATIC_ABT_HYPER2           258
#define IDS_DESCRIPTION1                259
#define IDS_DESCRIPTION2                260
#define IDS_DESCRIPTION3                261
#define IDS_DESCRIPTION4                262
#define IDS_DESCRIPTION5                263
#define IDS_DESCRIPTION6                264
#define IDS_DESCRIPTION7                265
#define IDS_DESCRIPTION8                266
#define IDS_DESCRIPTION9                267
#define IDS_DESCRIPTION10               268
#define IDS_DESCRIPTION11               269
#define IDS_WARN_ABORT_CONFIRM          270
#define IDS_MENU_HELP                   271
#define IDS_ERROR_DIRCT                 272
#define IDS_ERROR_DIRECT2               273
#define IDS_ERROR_FILE                  274
#define IDS_ERROR_PARAM                 275
#define IDS_ERROR_SIZE                  276

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
